-- CreateTable
CREATE TABLE "Country" (
    "id" SERIAL NOT NULL,
    "name_common" TEXT NOT NULL,
    "name_official" TEXT NOT NULL,
    "native_name_eng" TEXT NOT NULL,
    "tld" JSONB NOT NULL,
    "cca2" TEXT NOT NULL,
    "ccn3" TEXT NOT NULL,
    "cca3" TEXT NOT NULL,
    "independent" BOOLEAN NOT NULL,
    "status" TEXT NOT NULL,
    "un_member" BOOLEAN NOT NULL,
    "currencies" JSONB NOT NULL,
    "idd_root" TEXT NOT NULL,
    "idd_suffixes" JSONB NOT NULL,
    "capital" JSONB NOT NULL,
    "alt_spellings" JSONB NOT NULL,
    "region" TEXT NOT NULL,
    "languages" JSONB NOT NULL,
    "translations" JSONB NOT NULL,
    "latlng" JSONB NOT NULL,
    "landlocked" BOOLEAN NOT NULL,
    "area" DOUBLE PRECISION NOT NULL,
    "demonyms" JSONB NOT NULL,
    "flag" TEXT NOT NULL,
    "maps" JSONB NOT NULL,
    "population" INTEGER NOT NULL,
    "car_signs" JSONB NOT NULL,
    "car_side" TEXT NOT NULL,
    "timezones" JSONB NOT NULL,
    "continents" JSONB NOT NULL,
    "flags_png" TEXT NOT NULL,
    "flags_svg" TEXT NOT NULL,
    "coat_of_arms" JSONB NOT NULL,
    "start_of_week" TEXT NOT NULL,
    "capital_info_latlng" JSONB NOT NULL,

    CONSTRAINT "Country_pkey" PRIMARY KEY ("id")
);
